// 액션 정의
export const TEST = 'TEST';

export const GET_FOOTER_MSG = 'GET_FOOTER_MSG';
export const SET_FOOTER_MSG = 'SET_FOOTER_MSG';

export const SET_OEMBED_CONTENT = 'SET_OEMBED_CONTENT';
export const GET_OEMBED_CONTENT = 'GET_OEMBED_CONTENT';
export const FAIL_OEMBED_CONTENT = 'FAIL_OEMBED_CONTENT';

export const DELETE_OEMBED_CONTENT = 'DELETE_OEMBED_CONTENT';
